// Blog article data structure
interface ContentBlock {
    type: "h2" | "h3" | "p" | "ul" | "ol" | "tip" | "warning" | "checklist" | "cta";
    key: string; // Translation key like "blog.articles.electronics.intro"
    items?: string[]; // Array of translation keys
}

export interface BlogArticle {
    slug: string;
    titleKey: string;
    excerptKey: string;
    categoryKey: string;
    date: string;
    readTime: string;
    authorKey: string; 
    authorBioKey: string; 
    image: string;
    imageAltKey: string; 
    tags: string[]; 
    content: ContentBlock[];
    relatedSlugs: string[];
}

export interface BlogPost {
    slug: string;
    titleKey: string;
    excerptKey: string;
    categoryKey: string;
    date: string;
    readTime: string;
    heroImage: string;
    thumbnail: string;
    tags: string[];
}

// Full article data with content blocks - ALL USE TRANSLATION KEYS
export const blogArticles: Record<string, BlogArticle> = {
    "shipping-electronics-lithium-batteries": {
        slug: "shipping-electronics-lithium-batteries",
        titleKey: "blog.articles.electronics.title",
        excerptKey: "blog.articles.electronics.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-07-10",
        readTime: "8 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/Battery-Labels.jpg",
        imageAltKey: "blog.articles.electronics.imageAlt",
        tags: ["blog.tags.electronics", "blog.tags.lithiumBatteries", "blog.tags.iata"],
        content: [
            { type: "p", key: "blog.articles.electronics.intro" },
            { type: "h2", key: "blog.articles.electronics.h2_regulations" },
            { type: "p", key: "blog.articles.electronics.p_regulations" },
            { type: "warning", key: "blog.articles.electronics.warn_loose" },
            { type: "h3", key: "blog.articles.electronics.h3_allowed" },
            { type: "ul", key: "", items: [
                "blog.articles.electronics.ul_allowed_1",
                "blog.articles.electronics.ul_allowed_2",
                "blog.articles.electronics.ul_allowed_3",
                "blog.articles.electronics.ul_allowed_4"
            ]},
            { type: "h3", key: "blog.articles.electronics.h3_packing" },
            { type: "ol", key: "", items: [
                "blog.articles.electronics.ol_packing_1",
                "blog.articles.electronics.ol_packing_2",
                "blog.articles.electronics.ol_packing_3",
                "blog.articles.electronics.ol_packing_4",
                "blog.articles.electronics.ol_packing_5"
            ]},
            { type: "tip", key: "blog.articles.electronics.tip_photos" },
            { type: "h2", key: "blog.articles.electronics.h2_checklist" },
            { type: "checklist", key: "", items: [
                "blog.articles.electronics.check_1",
                "blog.articles.electronics.check_2",
                "blog.articles.electronics.check_3",
                "blog.articles.electronics.check_4",
                "blog.articles.electronics.check_5",
                "blog.articles.electronics.check_6"
            ]},
            { type: "h2", key: "blog.articles.electronics.h2_mistakes" },
            { type: "p", key: "blog.articles.electronics.p_mistakes" },
            { type: "cta", key: "blog.articles.electronics.cta" },
        ],
        relatedSlugs: ["air-freight-vs-ocean-freight", "packaging-fragile-items", "customs-duties-explained"],
    },
    "china-to-cameroon-complete-guide": {
        slug: "china-to-cameroon-complete-guide",
        titleKey: "blog.articles.chinacameroon.title",
        excerptKey: "blog.articles.chinacameroon.excerpt",
        categoryKey: "blog.categories.routes",
        date: "2026-07-08",
        readTime: "12 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/Port-of-Shanghai-China.webp",
        imageAltKey: "blog.articles.chinacameroon.imageAlt",
        tags: ["blog.tags.china", "blog.tags.cameroon", "blog.tags.africaTrade"],
        content: [
            { type: "p", key: "blog.articles.chinacameroon.intro" },
            { type: "h2", key: "blog.articles.chinacameroon.h2_methods" },
            { type: "p", key: "blog.articles.chinacameroon.p_methods" },
            { type: "h3", key: "blog.articles.chinacameroon.h3_express" },
            { type: "ul", key: "", items: [
                "blog.articles.chinacameroon.ul_express_1",
                "blog.articles.chinacameroon.ul_express_2",
                "blog.articles.chinacameroon.ul_express_3"
            ]},
            { type: "h3", key: "blog.articles.chinacameroon.h3_standard" },
            { type: "ol", key: "", items: [
                "blog.articles.chinacameroon.ol_standard_1",
                "blog.articles.chinacameroon.ol_standard_2",
                "blog.articles.chinacameroon.ol_standard_3",
                "blog.articles.chinacameroon.ol_standard_4"
            ]},
            { type: "warning", key: "blog.articles.chinacameroon.warn_formm" },
            { type: "h2", key: "blog.articles.chinacameroon.h2_docs" },
            { type: "p", key: "blog.articles.chinacameroon.p_docs" },
            { type: "checklist", key: "", items: [
                "blog.articles.chinacameroon.check_1",
                "blog.articles.chinacameroon.check_2",
                "blog.articles.chinacameroon.check_3",
                "blog.articles.chinacameroon.check_4",
                "blog.articles.chinacameroon.check_5"
            ]},
            { type: "tip", key: "blog.articles.chinacameroon.tip_consolidate" },
            { type: "cta", key: "blog.articles.chinacameroon.cta" },
        ],
        relatedSlugs: ["consolidation-save-money", "turkey-hub-trade-bridge", "customs-duties-explained"],
    },
    "aes-documentation-high-value": {
        slug: "aes-documentation-high-value",
        titleKey: "blog.articles.aes.title",
        excerptKey: "blog.articles.aes.excerpt",
        categoryKey: "blog.categories.customs",
        date: "2026-07-05",
        readTime: "6 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/customs-form.jpg",
        imageAltKey: "blog.articles.aes.imageAlt",
        tags: ["blog.tags.aes", "blog.tags.customs", "blog.tags.documentation"],
        content: [
            { type: "p", key: "blog.articles.aes.intro" },
            { type: "h2", key: "blog.articles.aes.h2_what" },
            { type: "p", key: "blog.articles.aes.p_what" },
            { type: "h2", key: "blog.articles.aes.h2_when" },
            { type: "p", key: "blog.articles.aes.p_when" },
            { type: "ol", key: "", items: [
                "blog.articles.aes.ol_when_1",
                "blog.articles.aes.ol_when_2",
                "blog.articles.aes.ol_when_3"
            ]},
            { type: "tip", key: "blog.articles.aes.tip" },
            { type: "h2", key: "blog.articles.aes.h2_how" },
            { type: "p", key: "blog.articles.aes.p_how" },
            { type: "cta", key: "blog.articles.aes.cta" },
        ],
        relatedSlugs: ["customs-duties-explained", "shipping-electronics-lithium-batteries"],
    },
    "air-freight-vs-ocean-freight": {
        slug: "air-freight-vs-ocean-freight",
        titleKey: "blog.articles.airVsOcean.title",
        excerptKey: "blog.articles.airVsOcean.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-07-02",
        readTime: "10 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/Sea-freight-vs-air-freight.jpg",
        imageAltKey: "blog.articles.airVsOcean.imageAlt",
        tags: ["blog.tags.airFreight", "blog.tags.oceanFreight", "blog.tags.comparison"],
        content: [
            { type: "p", key: "blog.articles.airVsOcean.intro" },
            { type: "h2", key: "blog.articles.airVsOcean.h2_comparison" },
            { type: "p", key: "blog.articles.airVsOcean.p_comparison" },
            { type: "h3", key: "blog.articles.airVsOcean.h3_air" },
            { type: "ul", key: "", items: [
                "blog.articles.airVsOcean.ul_air_1",
                "blog.articles.airVsOcean.ul_air_2",
                "blog.articles.airVsOcean.ul_air_3",
                "blog.articles.airVsOcean.ul_air_4"
            ]},
            { type: "h3", key: "blog.articles.airVsOcean.h3_ocean" },
            { type: "ul", key: "", items: [
                "blog.articles.airVsOcean.ul_ocean_1",
                "blog.articles.airVsOcean.ul_ocean_2",
                "blog.articles.airVsOcean.ul_ocean_3",
                "blog.articles.airVsOcean.ul_ocean_4"
            ]},
            { type: "tip", key: "blog.articles.airVsOcean.tip" },
            { type: "h2", key: "blog.articles.airVsOcean.h2_decide" },
            { type: "p", key: "blog.articles.airVsOcean.p_decide" },
            { type: "cta", key: "blog.articles.airVsOcean.cta" },
        ],
        relatedSlugs: ["consolidation-save-money", "china-to-cameroon-complete-guide"],
    },
    "avoiding-demurrage-detention": {
        slug: "avoiding-demurrage-detention",
        titleKey: "blog.articles.demurrage.title",
        excerptKey: "blog.articles.demurrage.excerpt",
        categoryKey: "blog.categories.tips",
        date: "2026-06-28",
        readTime: "7 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/container-clock.webp",
        imageAltKey: "blog.articles.demurrage.imageAlt",
        tags: ["blog.tags.demurrage", "blog.tags.detention", "blog.tags.fees"],
        content: [
            { type: "p", key: "blog.articles.demurrage.intro" },
            { type: "h2", key: "blog.articles.demurrage.h2_what" },
            { type: "p", key: "blog.articles.demurrage.p_what" },
            { type: "warning", key: "blog.articles.demurrage.warn" },
            { type: "h2", key: "blog.articles.demurrage.h2_tips" },
            { type: "ol", key: "", items: [
                "blog.articles.demurrage.ol_tips_1",
                "blog.articles.demurrage.ol_tips_2",
                "blog.articles.demurrage.ol_tips_3",
                "blog.articles.demurrage.ol_tips_4",
                "blog.articles.demurrage.ol_tips_5"
            ]},
            { type: "tip", key: "blog.articles.demurrage.tip" },
            { type: "cta", key: "blog.articles.demurrage.cta" },
        ],
        relatedSlugs: ["air-freight-vs-ocean-freight"],
    },
    "usa-to-europe-shipping-guide": {
        slug: "usa-to-europe-shipping-guide",
        titleKey: "blog.articles.usaEurope.title",
        excerptKey: "blog.articles.usaEurope.excerpt",
        categoryKey: "blog.categories.routes",
        date: "2026-06-25",
        readTime: "9 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/eiffel-tower-statue-of-liberty.jpg",
        imageAltKey: "blog.articles.usaEurope.imageAlt",
        tags: ["blog.tags.usa", "blog.tags.europe", "blog.tags.transatlantic"],
        content: [
            { type: "p", key: "blog.articles.usaEurope.intro" },
            { type: "h2", key: "blog.articles.usaEurope.h2_options" },
            { type: "p", key: "blog.articles.usaEurope.p_options" },
            { type: "h2", key: "blog.articles.usaEurope.h2_customs" },
            { type: "p", key: "blog.articles.usaEurope.p_customs" },
            { type: "cta", key: "blog.articles.usaEurope.cta" },
        ],
        relatedSlugs: ["customs-duties-explained"],
    },
    "customs-duties-explained": {
        slug: "customs-duties-explained",
        titleKey: "blog.articles.customsDuties.title",
        excerptKey: "blog.articles.customsDuties.excerpt",
        categoryKey: "blog.categories.customs",
        date: "2026-06-20",
        readTime: "5 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/custom-check.webp",
        imageAltKey: "blog.articles.customsDuties.imageAlt",
        tags: ["blog.tags.customs", "blog.tags.duties", "blog.tags.taxes"],
        content: [
            { type: "p", key: "blog.articles.customsDuties.intro" },
            { type: "h2", key: "blog.articles.customsDuties.h2_what" },
            { type: "p", key: "blog.articles.customsDuties.p_what" },
            { type: "h2", key: "blog.articles.customsDuties.h2_who" },
            { type: "p", key: "blog.articles.customsDuties.p_who" },
            { type: "tip", key: "blog.articles.customsDuties.tip" },
            { type: "cta", key: "blog.articles.customsDuties.cta" },
        ],
        relatedSlugs: ["aes-documentation-high-value"],
    },
    "consolidation-save-money": {
        slug: "consolidation-save-money",
        titleKey: "blog.articles.consolidation.title",
        excerptKey: "blog.articles.consolidation.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-06-18",
        readTime: "6 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/Die_Cut_Boxes.webp",
        imageAltKey: "blog.articles.consolidation.imageAlt",
        tags: ["blog.tags.consolidation", "blog.tags.costSavings", "blog.tags.efficiency"],
        content: [
            { type: "p", key: "blog.articles.consolidation.intro" },
            { type: "h2", key: "blog.articles.consolidation.h2_how" },
            { type: "p", key: "blog.articles.consolidation.p_how" },
            { type: "h2", key: "blog.articles.consolidation.h2_benefits" },
            { type: "ul", key: "", items: [
                "blog.articles.consolidation.ul_benefits_1",
                "blog.articles.consolidation.ul_benefits_2",
                "blog.articles.consolidation.ul_benefits_3",
                "blog.articles.consolidation.ul_benefits_4"
            ]},
            { type: "tip", key: "blog.articles.consolidation.tip" },
            { type: "cta", key: "blog.articles.consolidation.cta" },
        ],
        relatedSlugs: ["air-freight-vs-ocean-freight"],
    },
    "incoterms-2026-explained": {
        slug: "incoterms-2026-explained",
        titleKey: "blog.articles.incoterms.title",
        excerptKey: "blog.articles.incoterms.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-06-15",
        readTime: "11 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/shipping-contract.webp",
        imageAltKey: "blog.articles.incoterms.imageAlt",
        tags: ["blog.tags.incoterms", "blog.tags.tradeTerms", "blog.tags.contracts"],
        content: [
            { type: "p", key: "blog.articles.incoterms.intro" },
            { type: "h2", key: "blog.articles.incoterms.h2_what" },
            { type: "p", key: "blog.articles.incoterms.p_what" },
            { type: "h2", key: "blog.articles.incoterms.h2_common" },
            { type: "p", key: "blog.articles.incoterms.p_common" },
            { type: "cta", key: "blog.articles.incoterms.cta" },
        ],
        relatedSlugs: ["customs-duties-explained"],
    },
    "future-of-freight-forwarding": {
        slug: "future-of-freight-forwarding",
        titleKey: "blog.articles.future.title",
        excerptKey: "blog.articles.future.excerpt",
        categoryKey: "blog.categories.industry",
        date: "2026-06-10",
        readTime: "8 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/ai-warehouse.webp",
        imageAltKey: "blog.articles.future.imageAlt",
        tags: ["blog.tags.future", "blog.tags.technology", "blog.tags.ai"],
        content: [
            { type: "p", key: "blog.articles.future.intro" },
            { type: "h2", key: "blog.articles.future.h2_trends" },
            { type: "p", key: "blog.articles.future.p_trends" },
            { type: "cta", key: "blog.articles.future.cta" },
        ],
        relatedSlugs: ["shipping-electronics-lithium-batteries"],
    },
    "packaging-fragile-items": {
        slug: "packaging-fragile-items",
        titleKey: "blog.articles.fragile.title",
        excerptKey: "blog.articles.fragile.excerpt",
        categoryKey: "blog.categories.tips",
        date: "2026-06-05",
        readTime: "5 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/fragile-cover.webp",
        imageAltKey: "blog.articles.fragile.imageAlt",
        tags: ["blog.tags.packaging", "blog.tags.fragile", "blog.tags.protection"],
        content: [
            { type: "p", key: "blog.articles.fragile.intro" },
            { type: "h2", key: "blog.articles.fragile.h2_steps" },
            { type: "ol", key: "", items: [
                "blog.articles.fragile.ol_steps_1",
                "blog.articles.fragile.ol_steps_2",
                "blog.articles.fragile.ol_steps_3",
                "blog.articles.fragile.ol_steps_4",
                "blog.articles.fragile.ol_steps_5"
            ]},
            { type: "tip", key: "blog.articles.fragile.tip" },
            { type: "cta", key: "blog.articles.fragile.cta" },
        ],
        relatedSlugs: ["shipping-electronics-lithium-batteries"],
    },
    "turkey-hub-trade-bridge": {
        slug: "turkey-hub-trade-bridge",
        titleKey: "blog.articles.turkey.title",
        excerptKey: "blog.articles.turkey.excerpt",
        categoryKey: "blog.categories.routes",
        date: "2026-06-01",
        readTime: "7 min",
        authorKey: "Thuram Junior",
        authorBioKey: "",
        image: "/blog/cargo-skyline.webp",
        imageAltKey: "blog.articles.turkey.imageAlt",
        tags: ["blog.tags.turkey", "blog.tags.istanbul", "blog.tags.tradeHub"],
        content: [
            { type: "p", key: "blog.articles.turkey.intro" },
            { type: "h2", key: "blog.articles.turkey.h2_why" },
            { type: "p", key: "blog.articles.turkey.p_why" },
            { type: "h2", key: "blog.articles.turkey.h2_advantages" },
            { type: "ul", key: "", items: [
                "blog.articles.turkey.ul_advantages_1",
                "blog.articles.turkey.ul_advantages_2",
                "blog.articles.turkey.ul_advantages_3"
            ]},
            { type: "cta", key: "blog.articles.turkey.cta" },
        ],
        relatedSlugs: ["china-to-cameroon-complete-guide", "usa-to-europe-shipping-guide"],
    },
};

// Related articles data (lighter version for listing) - USES TRANSLATION KEYS
export const relatedArticlesData: BlogPost[] = [
    {
        slug: "shipping-electronics-lithium-batteries",
        titleKey: "blog.articles.electronics.title",
        excerptKey: "blog.articles.electronics.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-07-10",
        readTime: "8 min",
        heroImage: "/blog/Battery-Labels.jpg",
        thumbnail: "/blog/Battery-Labels.jpg",
        tags: ["blog.tags.electronics", "blog.tags.lithiumBatteries", "blog.tags.iata"],
    },
    {
        slug: "china-to-cameroon-complete-guide",
        titleKey: "blog.articles.chinacameroon.title",
        excerptKey: "blog.articles.chinacameroon.excerpt",
        categoryKey: "blog.categories.routes",
        date: "2026-07-08",
        readTime: "12 min",
        heroImage: "/blog/Port-of-Shanghai-China.webp",
        thumbnail: "/blog/Port-of-Shanghai-China.webp",
        tags: ["blog.tags.china", "blog.tags.cameroon", "blog.tags.africaTrade"],
    },
    {
        slug: "aes-documentation-high-value",
        titleKey: "blog.articles.aes.title",
        excerptKey: "blog.articles.aes.excerpt",
        categoryKey: "blog.categories.customs",
        date: "2026-07-05",
        readTime: "6 min",
        heroImage: "/blog/customs-form.jpg",
        thumbnail: "/blog/customs-form.jpg",
        tags: ["blog.tags.aes", "blog.tags.customs", "blog.tags.documentation"],
    },
    {
        slug: "air-freight-vs-ocean-freight",
        titleKey: "blog.articles.airVsOcean.title",
        excerptKey: "blog.articles.airVsOcean.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-07-02",
        readTime: "10 min",
        heroImage: "/blog/Sea-freight-vs-air-freight.jpg",
        thumbnail: "/blog/Sea-freight-vs-air-freight.jpg",
        tags: ["blog.tags.airFreight", "blog.tags.oceanFreight", "blog.tags.comparison"],
    },
    {
        slug: "avoiding-demurrage-detention",
        titleKey: "blog.articles.demurrage.title",
        excerptKey: "blog.articles.demurrage.excerpt",
        categoryKey: "blog.categories.tips",
        date: "2026-06-28",
        readTime: "7 min",
        heroImage: "/blog/container-clock.webp",
        thumbnail: "/blog/container-clock.webp",
        tags: ["blog.tags.demurrage", "blog.tags.detention", "blog.tags.fees"],
    },
    {
        slug: "usa-to-europe-shipping-guide",
        titleKey: "blog.articles.usaEurope.title",
        excerptKey: "blog.articles.usaEurope.excerpt",
        categoryKey: "blog.categories.routes",
        date: "2026-06-25",
        readTime: "9 min",
        heroImage: "/blog/eiffel-tower-statue-of-liberty.jpg",
        thumbnail: "/blog/eiffel-tower-statue-of-liberty.jpg",
        tags: ["blog.tags.usa", "blog.tags.europe", "blog.tags.transatlantic"],
    },
    {
        slug: "customs-duties-explained",
        titleKey: "blog.articles.customsDuties.title",
        excerptKey: "blog.articles.customsDuties.excerpt",
        categoryKey: "blog.categories.customs",
        date: "2026-06-20",
        readTime: "5 min",
        heroImage: "/blog/custom-check.webp",
        thumbnail: "/blog/custom-check.webp",
        tags: ["blog.tags.customs", "blog.tags.duties", "blog.tags.taxes"],
    },
    {
        slug: "consolidation-save-money",
        titleKey: "blog.articles.consolidation.title",
        excerptKey: "blog.articles.consolidation.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-06-18",
        readTime: "6 min",
        heroImage: "/blog/Die_Cut_Boxes.webp",
        thumbnail: "/blog/Die_Cut_Boxes.webp",
        tags: ["blog.tags.consolidation", "blog.tags.costSavings"],
    },
    {
        slug: "incoterms-2026-explained",
        titleKey: "blog.articles.incoterms.title",
        excerptKey: "blog.articles.incoterms.excerpt",
        categoryKey: "blog.categories.guides",
        date: "2026-06-15",
        readTime: "11 min",
        heroImage: "/blog/shipping-contract.webp",
        thumbnail: "/blog/shipping-contract.webp",
        tags: ["blog.tags.incoterms", "blog.tags.tradeTerms"],
    },
    {
        slug: "future-of-freight-forwarding",
        titleKey: "blog.articles.future.title",
        excerptKey: "blog.articles.future.excerpt",
        categoryKey: "blog.categories.industry",
        date: "2026-06-10",
        readTime: "8 min",
        heroImage: "/blog/ai-warehouse.webp",
        thumbnail: "/blog/ai-warehouse.webp",
        tags: ["blog.tags.future", "blog.tags.technology", "blog.tags.ai"],
    },
    {
        slug: "packaging-fragile-items",
        titleKey: "blog.articles.fragile.title",
        excerptKey: "blog.articles.fragile.excerpt",
        categoryKey: "blog.categories.tips",
        date: "2026-06-05",
        readTime: "5 min",
        heroImage: "/blog/fragile-cover.webp",
        thumbnail: "/blog/fragile-cover.webp",
        tags: ["blog.tags.packaging", "blog.tags.fragile", "blog.tags.protection"],
    },
    {
        slug: "turkey-hub-trade-bridge",
        titleKey: "blog.articles.turkey.title",
        excerptKey: "blog.articles.turkey.excerpt",
        categoryKey: "blog.categories.routes",
        date: "2026-06-01",
        readTime: "7 min",
        heroImage: "/blog/cargo-skyline.webp",
        thumbnail: "/blog/cargo-skyline.webp",
        tags: ["blog.tags.turkey", "blog.tags.istanbul", "blog.tags.tradeHub"],
    },
];
